[connections.AIVEN]
url = "postgresql+psycopg2://avnadmin:AVNS__BW4AupQW-WFTiEG6xW@pg-3cf0100c-eu-sou-rogerio-sb.g.aivencloud.com:12722/defaultdb"

[connections.AIVEN2]
url = "postgresql://avnadmin:AVNS__BW4AupQW-WFTiEG6xW@pg-3cf0100c-eu-sou-rogerio-sb.g.aivencloud.com:12722/defaultdb"